pipeline {
    agent any
    stages {
        stage('Load the dataset from Kaggle') {
            steps {
                sh "python lab2/data.py"
            }
        }
        stage('Train the model') {
            steps {
                sh "python lab2/train_model.py"
            }
        }
        stage('Test the model') {
            steps {
                sh "python lab2/test_model.py"
            }
        }
    }
}