version: '1'
services:
  model:
    build:
      context: model/
      dockerfile: Dockerfile
    image: molokhovdmitry/lab3-model
    volumes:
      - $HOME/.kaggle/kaggle.json:/root/.kaggle/kaggle.json
      - ../models/:/app/models/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  app:
    build:
      context: app/
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    image: molokhovdmitry/lab3-app
    volumes:
      - ../models/:/app/models/
