name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    environment: lab3

    steps:
    - uses: actions/checkout@v4

    

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push the lab3-model Docker image
      uses: docker/build-push-action@v5
      with:
        context: lab3/model
        push: true
        tags: molokhovdmitry/lab3-model:${{ github.sha }}
    
    - name: Build and push the lab3-app Docker image
      uses: docker/build-push-action@v5
      with:
        context: lab3/app
        push: true
        tags: molokhovdmitry/lab3-app:${{ github.sha }}
